version: '2'
services:
  php:
    build: ./php/
    volumes:
      - ./www/:/app
    working_dir: /app
  redis:
    image: redis
    depends_on:
      - php
  web:
    build: ./nginx/
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./www/:/app
    labels:
      - sh.acme.autoload.domain=${domain}
    depends_on:
      - php
    ports:
      - 443:443
  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    command: daemon
    volumes:
      - ./acmeout:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DP_Id=${DP_Id}
      - DP_Key=${DP_Key}
      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=${domain}
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE="/etc/nginx/conf.d/conf/ssl/${domain}/key.pem"
      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/nginx/conf.d/conf/ssl/${domain}/cert.pem"
      - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/nginx/conf.d/conf/ssl/${domain}/ca.pem"
      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/nginx/conf.d/conf/ssl/${domain}/full.pem"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="nginx -s reload"